trigger:
  branches:
    include:
      - main

pool:
  name: aws-cdk-app
  demands:
    - agent.name -equals cdk-syndicate

variables:
  - group: vars 21-Sep
  - name: ROLE_ARN
    value: arn:aws:iam::$(AWS_ACCOUNT_ID):role/$(ROLE_NAME)

steps:

- script: |
   if ! [ -x "$(command -v jq)" ]; then
    printf "%sPlease install jq %s\\n" 
    exit 1
   elif ! [ -x "$(command -v cdk)" ]; then
    printf "%sPlease install cdk %s\\n" 
    exit 1
   fi
  displayName: Create virtual environment and install dependencies

- script: |
    ASSUMED_CREDENTIALS=$(aws sts assume-role --role-arn arn:aws:iam::317048034783:role/ado-cdk-app --role-session-name cdk-app-cdployment-ado --external-id dYYEBxxUk97WmbYy)
    echo ${ASSUMED_CREDENTIALS}
    AWS_ACCESS_KEY_ID=$(echo "${ASSUMED_CREDENTIALS}" | jq -r .Credentials.AccessKeyId)
    AWS_SECRET_ACCESS_KEY=$(echo "${ASSUMED_CREDENTIALS}" | jq -r .Credentials.SecretAccessKey)
    AWS_SESSION_TOKEN=$(echo "${ASSUMED_CREDENTIALS}" | jq -r .Credentials.SessionToken)

    export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

    printf "\\n%sRole assumed%s"
  displayName: Assume role with external id

- script: |
   python3 -m venv env
   source ./env/bin/activate
   pip install -r requirements.txt
  displayName: Create virtual environment and install dependencies

- script: |
   cdk bootstrap $(AWS_ACCOUNT_ID)/$(AWS_REGION)
  displayName: CDK Bootstrap

- script: |
   cdk deploy 
  displayName: CDK Deploy
